---
abstract: 'Plugin of SQL::Maker for making SQL contained `JOIN`'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Maker-Plugin-JoinSelect
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  SQL::Maker::Plugin::JoinSelect:
    file: lib/SQL/Maker/Plugin/JoinSelect.pm
    version: 0.01
requires:
  SQL::Maker: 0.12
  perl: 5.008001
resources:
  bugtracker: https://github.com/Songmu/p5-SQL-Maker-Plugin-JoinSelect/issues
  homepage: https://github.com/Songmu/p5-SQL-Maker-Plugin-JoinSelect
  repository: git://github.com/Songmu/p5-SQL-Maker-Plugin-JoinSelect.git
version: 0.01
